### ISSUE TITLE
I tried following the instruction on MacOS and get the error described below

### ISSUE THREAD

**Issue by JustinGOSSES** [pemn/vtk_reserves#1]
I tried following the instruction on MacOS and get the error described below when I ran `python -m vtk_reserve` in the root directory of the repo after installing pyvista.

```
(streamlit) JustinGosses_per:vtk_reserves justingosses$ python -m vtk_reserves
Traceback (most recent call last):
  File "/Users/justingosses/anaconda/envs/streamlit/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/justingosses/anaconda/envs/streamlit/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/justingosses/Code/junk/vtk_reserves/vtk_reserves.py", line 129, in <module>
    usage_gui(__doc__)
  File "/Users/justingosses/Code/junk/vtk_reserves/_gui.py", line 1226, in usage_gui
    AppTk(usage).mainloop()
  File "/Users/justingosses/Code/junk/vtk_reserves/_gui.py", line 2067, in __init__
    self._iconfile = Branding().name
  File "/Users/justingosses/Code/junk/vtk_reserves/_gui.py", line 2191, in __init__
    self._choice = os.environ['USERDOMAIN']
  File "/Users/justingosses/anaconda/envs/streamlit/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'USERDOMAIN'
```

I suspect the problem is with this line of code in https://github.com/pemn/vtk_reserves/blob/main/_gui.py

```
# images for window icon and watermark
class Branding(object):
  _gc = []
  def __init__(self, f='ICO', size=None, choice=None):
    if choice is None:
      self._choice = os.environ['USERDOMAIN']
    else:
      self._choice = choice

    self._format = f
    
    self._image = Image.new('RGBA', (800, 800))
    draw = ImageDraw.Draw(self._image)

    if self._choice=='VALENET':
      # Vale logo
      draw.polygon((430, 249, 397,698, 803,160,  766,139, 745,132, 727,130, 692,130, 655,142, 618,160, 571,188, 524,216, 477,236), "#eaab13")
      draw.chord((-80,105, 413,588), 228, 312, "#008f83")
      draw.polygon((0,165, 397,698, 720,270, 454,270, 454,270, 429,248, 328,165), "#008f83")
      draw.chord((403,-40, 770,327), 44, 136, "#eaab13")
    else:
      # open souce logo
      draw.pieslice([40, 40, 760, 760], 110, 70, '#3fa648')
      draw.ellipse([288, 288, 512, 512], Image.ANTIALIAS)
```

**Comment by pemn** [comment]
It was looking for the enviroment variable USERDOMAIN which is Windows only. I added a check to avoid this error.
